export const data = [
  {
    id: "1234",
    firmName: "Verma GmbH",
    ContactNo: "9123458844",
    email: "infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
  {
    id: "1234",
    firmName: "Facebook",
    ContactNo: "9123458844",
    email: "Facebook infoavermass.de",
    state: "Nebraska",
  },
];

//50 us states array
export const states = [
  "Alabama",
  "Alaska",
  "Arizona",
  "Arkansas",
  "California",
  "Colorado",
  "Connecticut",
  "Delaware",
  "Florida",
  "Georgia",
  "Hawaii",
  "Idaho",
  "Illinois",
  "Indiana",
  "Iowa",
  "Kansas",
  "Kentucky",
  "Louisiana",
  "Maine",
  "Maryland",
  "Massachusetts",
  "Michigan",
  "Minnesota",
  "Mississippi",
  "Missouri",
  "Montana",
  "Nebraska",
  "Nevada",
  "New Hampshire",
  "New Jersey",
  "New Mexico",
  "New York",
  "North Carolina",
  "North Dakota",
  "Ohio",
  "Oklahoma",
  "Oregon",
  "Pennsylvania",
  "Rhode Island",
  "South Carolina",
  "South Dakota",
  "Tennessee",
  "Texas",
  "Utah",
  "Vermont",
  "Virginia",
  "Washington",
  "West Virginia",
  "Wisconsin",
  "Wyoming",
  "Puerto Rico",
];
